[package]
name = "ziggurat"
version = "0.1.0"
authors = ["Niklas Long <niklas@equilibrium.co>, Mirko von Leipzig <mirko@equilibrium.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5"
async-trait = "0.1.50"
chrono = "0.4"
comfy-table = "2.1.0"
hex = "0.4.3"
histogram = "0.6.9"
home = "0.5.3"
lazy_static = "1.4.0"
metrics = "0.16.0"
parking_lot = "0.11.1"
pea2pea = "0.20.3"
rand = "0.8.3"
rand_chacha = "0.3.0"
sha2 = "0.9.3"
toml = "0.5.8"

[dependencies.serde]
version = "1"
features = [ "derive" ]

[dependencies.tokio]
version = "1"
features = [ "full" ]

[dependencies.tracing]
version = "0.1"
default-features = false

[dependencies.tracing-subscriber]
version = "0.2.18"
features = [ "env-filter", "fmt" ]

