name: crawler

on:
  workflow_dispatch:    
  push:
    branches: [ "crawler-ci" ]

jobs:
  install-zcashd:
    runs-on: ubuntu-latest
    steps:
      - name: clone zcashd
        run: git clone https://github.com/zcash/zcash
      - name: build zcashd
        run: |
          cd zcash
          ./zcutil/build.sh -j$(nproc)
      - uses: actions/upload-artifact@v2
        with:
          name: zcashd-fetch-params
          path: ./zcash/zcutil/fetch-params.sh
      - uses: actions/upload-artifact@v2
        with:
          name: zcashd-executable
          path: ./zcash/src/zcashd

  crawl-network:
    runs-on: ubuntu-latest
    needs: [ install-zcashd ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/download-artifact@v3
        with:
          name: zcashd-fetch-params
          path: ./zcash
      - uses: actions/download-artifact@v3
        with:
          name: zcashd-executable
          path: ./zcash
      - name: Create ~/.zcash/zcash.conf
        run: |
          mkdir ~/.zcash/
          touch ~/.zcash/zcash.conf
          echo bind=127.0.0.1:12345 > ~/.zcash/zcash.conf
      - name: Fetch zcashd params
        run: |
          chmod +x zcash/fetch-params.sh
          ./zcash/fetch-params.sh
      - name: Begin crawling
        run: |
          chmod +x zcash/zcashd
          ./zcash/zcashd &
          cargo run --release --features crawler --bin crawler -- --seed-addrs 127.0.0.1:12345 &
          # Send SIGINT after 1 min.
          sleep 60s
          ps
          killall -INT cargo
          cat crawler-log.txt
