name: zcashd

on:
  workflow_dispatch:    
  push:
    branches: [ "zcash-ci" ]
  # pull_request:
  #   branches: [ main ]

jobs:
  install-zcashd:
    runs-on: ubuntu-latest
    steps:
      - name: clone zcashd
        run: git clone https://github.com/zcash/zcash
      - name: fetch params
        run: |
          cd zcash
          ./zcutil/fetch-params.sh
      - name: build zcashd
        run: |
          cd zcash
          ./zcutil/build.sh -j$(nproc)
      - uses: actions/upload-artifact@v2
        with:
          name: zcashd-executable
          path: ./zcash/src/zcashd

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --no-run
      - uses: actions/upload-artifact@v2
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat-*

  test-zcashd:
    runs-on: ubuntu-latest
    needs: [ check, install-zcashd ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: zcashd-executable
          path: ./zcashd
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - name: Create ~/.ziggurat/config.toml
        run: |
          mkdir ~/.ziggurat/
          touch ~/.ziggurat/config.toml
          echo kind = \"zcashd\" >> ~/.ziggurat/config.toml
          echo path = \"/home/runner/work/ziggurat/ziggurat/zcashd\" >> ~/.ziggurat/config.toml
          echo start_command = \"./zcashd -debug=1 -printtoconsole -logips=1 -dnsseed=0 -dns=0 -listenonion=0\" >> ~/.ziggurat/config.toml
          cat ~/.ziggurat/config.toml
      - run: |
          rm ./ziggurat/*.d
          mv ./ziggurat/ziggurat-* ziggurat_test
          chmod +x ziggurat_test
          chmod +x zcashd/zcashd
          pwd
          ls -Rla
          RUST_BACKTRACE=1 ./ziggurat_test --test-threads=1 --nocapture -Z unstable-options --format json
