name: zcashd

on:
  workflow_dispatch:    
  push:
    branches: [ "zcash-ci" ]
  # pull_request:
  #   branches: [ main ]

jobs:
  install-zcashd:
    runs-on: ubuntu-latest
    steps:
      - name: clone zcashd
        run: git clone https://github.com/zcash/zcash
      - name: fetch params
        run: |
          cd zcash
          ./zcutil/fetch-params.sh
      - name: build zcashd
        run: |
          cd zcash
          ./zcutil/build.sh -j$(nproc)

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets

  test:
    runs-on: ubuntu-latest
    needs: [ check, install-zcashd ]
    steps:
      - run: ls zcash