name: zcashd

on:
  workflow_dispatch:    
  push:
    branches: [ "zcash-ci" ]
  # pull_request:
  #   branches: [ main ]

jobs:
  install-zebra:
    runs-on: ubuntu-latest
    steps:
      - name: clone zebra
        run: git clone https://github.com/ZcashFoundation/zebra
      - name: build zcashd
        run: |
          cd zebra
          cargo +stable run --release download
          cargo +stable run --release -- --verbose start
      - uses: actions/upload-artifact@v2
        with:
          name: zebra-executable
          path: ./target/release/zebrad

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --no-run
      - uses: actions/upload-artifact@v2
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat-*

  test-zebra:
    runs-on: ubuntu-latest
    needs: [ check, install-zebra ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: zebra-executable
          path: ./zebrad
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - run: |
          ./zebrad --verbose start
          $ZEBRA_PID="$!"
          echo $ZEBRA_PID
          ./ziggurat
          kill $ZEBRA_PID