name: Zebra

on:
  workflow_dispatch:    
  push:
    branches: [ "main" ]

jobs:
  build-zebra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ZcashFoundation/zebra
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: build Zebra and download artifacts
        run: cargo +stable build --release
      - uses: actions/upload-artifact@v2
        with:
          name: zebra-executable
          path: ./target/release/zebrad

  build-ziggurat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --no-run
      - uses: actions/upload-artifact@v2
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat-*

  test-zebra:
    runs-on: ubuntu-latest
    needs: [ build-zebra, build-ziggurat ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: zebra-executable
          path: ./zebrad
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - run: |
          chmod +x ./zebrad/zebrad
      - name: Create ~/.ziggurat/config.toml
        run: |
          git clone https://github.com/ZcashFoundation/zebra
          mkdir ~/.ziggurat/
          touch ~/.ziggurat/config.toml
          echo kind = \"zebra\" >> ~/.ziggurat/config.toml
          echo path = \"zebra\" >> ~/.ziggurat/config.toml
          echo start_command = \"../zebrad/zebrad start\" >> ~/.ziggurat/config.toml
      - name: Download Zebra params
        run: |
          ./zebrad/zebrad download
      - run: |
          rm ./ziggurat/*.d
          mv ./ziggurat/ziggurat-* ziggurat_test
          chmod +x ziggurat_test
          ./ziggurat_test --test-threads=1 -Z unstable-options --format json
